### ISSUE TITLE
[Help wanted] An extremely basic and trivial example for locking a file?

### ISSUE THREAD

**Issue by audunolsen** [ORESoftware/live-mutex#93]
## Description

I found this library when I stumbled across [a question](https://stackoverflow.com/questions/39988997/locking-a-file-for-read-write-with-node-js) on stackoverflow asking for how to handle file lockingin in node, where the author of this package answered with "[for even this simple use case, live-mutex serves you better than alternatives like lockfile and warlock](https://stackoverflow.com/a/45641071/5754578)" (I'm paraphrasing). When I visited the github to read up on the docs I don't really see anything about file locking. Only heavy mutex-lingo which I don't really understand at this point.

If this is could be used as an alternative to lockfile, then could you provide a simple, super trivial example of just locking a single file so no other processes can write on it?

**Comment by ORESoftware** [comment]
sorry didn't see this until now. if you are on a single machine, lockfile is probably sufficient. are you familiar with docker?

here is an example with async/await:
https://github.com/ORESoftware/live-mutex-examples/blob/master/src/dual/repro.ts

but since you ultimately will want the broker in it's own process, launch the broker with:
https://github.com/ORESoftware/live-mutex-examples/blob/master/src/server/cli.ts

and then use this code to request locks:
https://github.com/ORESoftware/live-mutex-examples/blob/master/src/client/async-await.ts

**Comment by ORESoftware** [comment]
any luck?
